const ids = ["thema", "zeit", "fakten", "e1", "e2", "e3", "plan", "original", "staerke", "abschnitt"];
const first = "Schreibe mit uns eine neue Heidi-Erzählung von 700–900 Wörtern. Beschränke dich auf einen Hauptkonflikt und höchstens drei Szenen. Heidi muss selbst handeln. Erfinde einen neuen Verlauf; fasse keine bekannte Episode nacherzählend zusammen. Dies ist eine heutige Neuschöpfung, kein Original von Spyri.\n\nErzählform und Zeitpunkt: [Ergänzung oder Fortschreibung; genauer Anschluss]\nDrei feste Tatsachen aus dem Roman: [einsetzen]\nDrei Erkenntnisse mit Belegen und Herkunft: [E1, E2, E3 einsetzen]\nUnser Plan aus fünf Schritten: [einsetzen]\nOriginalpassage als sprachliches Vorbild: [80–120 Wörter mit Fundstelle]\n\nHalte dich an unseren Plan. Lass die Erkenntnisse Entscheidungen, Beziehungen oder Folgen prägen. Schreibe sie nicht als Schulwissen in Dialoge. Figuren dürfen nur wissen, was sie erfahren haben; Motive und Missverständnisse müssen nachvollziehbar sein. Erfinde keine angeblichen Romanfakten, Quellen oder Zitate. Nutze spätere Wirkungsgeschichte nur als Gestaltungsanregung, nicht als Wissen der historischen Figuren.\n\nVerbinde Wahrnehmung, innere Bewegung und Handlung. Schaffe Atmosphäre durch wenige bedeutsame Einzelheiten. Kinder sprechen konkret und unmittelbar. Verwende Schweizer Rechtschreibung mit ss und Guillemets («…»), mit zurückhaltendem regionalem Ton, ohne künstlichen Dialekt. Orientiere dich an der Originalpassage, ohne Sätze zu kopieren. Zeige am Ende eine Veränderung; vermeide eine bloss angehängte Moral.\n\nWenn im Material ein wesentlicher Widerspruch steckt, nenne ihn kurz statt ihn stillschweigend zu erfinden. Sonst gib Titel und Erzählung aus. Nenne danach in höchstens 80 Wörtern, wo E1 bis E3 wirksam werden und welche Romanangabe wir nochmals prüfen müssen.";
const second = "Prüfe nur unseren folgenden Abschnitt. Unsere Erkenntnis lautet: [einsetzen]. Markiere höchstens zwei konkrete Probleme bei Plausibilität oder Sprache und erkläre sie kurz. Schreibe höchstens eine passende Alternative. Erhalte diese gelungene Stelle wortgleich: [einsetzen]. Maximal 180 Wörter Antwort. Abschnitt: [einsetzen].";
const $ = id => document.getElementById(id);
const storageKey = 'heidi-schreibwerkstatt-v1';
const values = () => Object.fromEntries(ids.map(id => [id, $(id).value]));
const message = text => $('promptstatus').textContent = text;
function apply(data) { for (const id of ids) if (typeof data[id] === 'string') $(id).value = data[id]; }
function save() { try { localStorage.setItem(storageKey,JSON.stringify(values())); $('savestatus').textContent='In diesem Browser gespeichert. Sichert zusätzlich eine Datei.'; } catch { $('savestatus').textContent='Browserspeicherung nicht möglich. Bitte Notizen herunterladen.'; } }
try { const stored=JSON.parse(localStorage.getItem(storageKey)||'{}');if(stored&&typeof stored==='object')apply(stored); } catch { $('savestatus').textContent='Vorhandene Notizen konnten nicht geladen werden.'; }
$('notes').addEventListener('input',save);
function build() {
const required=['zeit','fakten','e1','e2','e3','plan','original'];
const missing=required.filter(id=>!$(id).value.trim());
if(missing.length){message('Bitte zuerst alle Felder bis zur Originalpassage ausfüllen.');$(missing[0]).focus();return;}
const replacements=[$('zeit').value,$('fakten').value,[1,2,3].map(i=>'E'+i+': '+$('e'+i).value).join('\n'),$('plan').value,$('original').value];
let position=0;
const text=first.replace(/\[[^\]]+\]/g,()=>replacements[position++]);
$('result').value=text;message('Prompt erstellt. Inhalt prüfen, dann kopieren.');
}
$('build').addEventListener('click',build);
$('review').addEventListener('click',()=>{if(!$('abschnitt').value.trim()){message('Bitte den zu prüfenden Abschnitt eintragen.');$('abschnitt').focus();return;}const replacements=[[1,2,3].map(i=>$('e'+i).value).filter(Boolean).join('\n'),$('staerke').value||'Keine festgelegt',$('abschnitt').value];let position=0;$('result').value=second.replace(/\[einsetzen\]/g,()=>replacements[position++]);message('Prüfprompt erstellt.');});
$('copy').addEventListener('click',async()=>{if(!$('result').value){message('Zuerst einen Prompt erstellen.');return;}try{await navigator.clipboard.writeText($('result').value);message('Kopiert. Im Textchat einfügen.');}catch{$('result').focus();$('result').select();message('Bitte mit ⌘ + C oder Strg + C kopieren.');}});
$('export').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({version:1,...values()},null,2)],{type:'application/json'});const a=document.createElement('a');const url=URL.createObjectURL(blob);a.href=url;a.download='heidi-gruppennotizen.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
$('import').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>1000000)throw Error('too large');const data=JSON.parse(await f.text());if(!data||typeof data!=='object'||!ids.some(id=>typeof data[id]==='string'))throw Error('invalid');if(ids.some(id=>$(id).value)&&!confirm('Die vorhandenen Eingaben durch die geladenen Notizen ergänzen oder ersetzen?'))return;apply(data);save();}catch{$('savestatus').textContent='Datei konnte nicht geladen werden. Bitte eine exportierte Notizdatei wählen.'}finally{e.target.value='';}});
